### ISSUE TITLE
Подскажите 

### ISSUE THREAD

**Issue by aukrohero** [3lfar7/tripadvparser#1]
```
python3 tripadvparser.py fetch_hotels
creating tables
fetching main services: /Hotels-g294474-Kiev-Hotels.html
Traceback (most recent call last):
  File "tripadvparser.py", line 943, in <module>
    ta_parser.fetch_hotels()
  File "tripadvparser.py", line 729, in fetch_hotels
    self.fetch_main_services()
  File "tripadvparser.py", line 722, in fetch_main_services
    for name in self.zip_translation(self.parse_services()):
  File "tripadvparser.py", line 265, in parse_services
    parser(html)
  File "/home/m/Documents/japantokyohotels/tripadvparser-master/htmlparser/__init__.py", line 183, in __call__
    self.data[name] = collector.clean(name, self.data[name])
  File "/home/m/Documents/japantokyohotels/tripadvparser-master/htmlparser/__init__.py", line 134, in clean
    name, len(result), self.min_pass_count)
htmlparser.CollectorError: the number of collector ('services') passes (0) is less than the minimum number of passes (1)
```

**Comment by 3lfar7** [comment]
Парсер был актуальный на 20.07.17. С того времени что то изменилось на сайте tripadvisor. Обновление парсера для текущего состояния сайта будет через 1-2 недели.
